export const cbmCourses = [
  {
    id: 1,
    level: "Level 1",
    title: "CBM Foundations: Hospital Billing Anatomy™",
    whoFor: "Freshers and billing execs (0–2 yrs)",
    image:
      "https://media.istockphoto.com/id/1429005048/photo/scientist-woman-tablet-research-and-test-tube-innovation-analytics-and-expert-planning-in.webp?a=1&b=1&s=612x612&w=0&k=20&c=L7YU841kGO_ZWqvkcgYeOboAvZTnT7fVNgdLxFSvdOc=",
    duration: "6 weeks",
    outcomes: [
      "Decode the complete billing workflow from registration to final bill",
      "Prepare accurate estimates, generate bills, and manage cashless files",
      "Eliminate basic documentation and data entry errors",
    ],
    keyModules: [
      "Patient onboarding",
      "Charge capture",
      "Coding basics",
      "TPA basics",
      "Discharge billing",
      "Consumables",
      "Final bill QA",
      "Basic compliance",
    ],
    mode: "Hybrid (recorded + live doubt clinics)",
    assessment: "Billing file audit + SOP checklist",
    outcomeCertificate:
      "CBM Level 1 Certificate; ready for Hospital Billing Executive roles",
  },
  {
    id: 2,
    level: "Level 2",
    title: "CBM Claims & TPA Coordination™",
    whoFor: "Billing/TPA teams (1–3 yrs)",
    image: "/images/default-course.jpg",
    duration: "8 weeks",
    outcomes: [
      "Drive pre-auth to discharge approvals end-to-end",
      "Standardize communication templates to reduce pendency",
      "Cut turnaround time (TAT) with better stakeholder handoffs",
    ],
    keyModules: [
      "Pre-auth",
      "Approvals",
      "Claim documentation",
      "Insurer/TPA SLAs",
      "Query handling",
      "Discharge TAT",
      "Communication protocols",
    ],
    mode: "Hybrid (recorded + live doubt clinics)",
    assessment: "Live case simulation + query closure tracker",
    outcomeCertificate:
      "CBM Level 2; TPA Coordinator / Claims Processor readiness",
  },
  {
    id: 3,
    level: "Level 3",
    title: "CBM Denial Management & RCM Analytics™",
    whoFor: "RCM analysts and senior execs (2–5 yrs)",
    image: "/images/default-course.jpg",
    duration: "10 weeks",
    outcomes: [
      "Build a Denial taxonomy, root-cause analysis (RCA), and preventive playbooks",
      "Track A/R buckets, aging, recovery, and weekly KPI dashboards",
      "Collaborate with coding, finance, and clinical teams using data",
    ],
    keyModules: [
      "Denial types",
      "RCA (Root Cause Analysis)",
      "Recovery workflows",
      "A/R & aging",
      "Dashboards",
      "Cross-functional RCA",
    ],
    mode: "Hybrid (recorded + live doubt clinics)",
    assessment: "Denial-prevention capstone + dashboard demo",
    outcomeCertificate: "CBM Level 3; RCM Analyst / Denial Specialist",
  },
  {
    id: 4,
    level: "Level 4",
    title: "CBM Compliance, Audit & Controls™",
    whoFor: "Seniors aiming for audit-ready operations",
    image: "/images/default-course.jpg",
    duration: "8 weeks",
    outcomes: [
      "Implement checklists, SOPs, and internal controls aligned to hospital policies",
      "Prepare for payer/governance audits and documentation standards",
    ],
    keyModules: [
      "Policy frameworks",
      "Audit readiness",
      "Exception handling",
      "Regulatory notes",
      "Documentation control",
    ],
    mode: "Hybrid (recorded + live doubt clinics)",
    assessment: "Mock audit + corrective action plan",
    outcomeCertificate: "CBM Level 4; Compliance Lead / Audit Coordinator",
  },
  {
    id: 5,
    level: "Level 5",
    title: "CBM Revenue Assurance & Strategy™",
    whoFor: "Team leads, finance-RCM bridge roles",
    image: "/images/default-course.jpg",
    duration: "12 weeks",
    outcomes: [
      "Identify and fix leakage points across the patient journey",
      "Align billing, coding, materials, and finance on P&L impact",
      "Drive weekly governance with CFO/COO using metric trees",
    ],
    keyModules: [
      "Revenue leakage map",
      "Pricing & packages",
      "Materials & implants",
      "Contracts",
      "Recovery governance",
      "Monthly close",
    ],
    mode: "Hybrid (recorded + live doubt clinics)",
    assessment: "Revenue-assurance project with quantified savings",
    outcomeCertificate: "CBM Level 5; Revenue Assurance Specialist / Team Lead",
  },
  {
    id: 6,
    level: "Level 6",
    title: "CBM Expert Practicum & Capstone™",
    whoFor: "Managers & future RCM leaders",
    image: "/images/default-course.jpg",
    duration: "16 weeks",
    outcomes: [
      "Lead a cross-functional RCM transformation in a live or simulated environment",
      "Present board-grade dashboards, policies, and outcomes",
    ],
    keyModules: [
      "Change management",
      "OKRs",
      "Automation roadmap (OCR/NLP/RPA)",
      "Vendor management",
      "Governance",
    ],
    mode: "Hybrid (recorded + live doubt clinics)",
    assessment: "Capstone (audit-proof SOPs, dashboards, savings case)",
    outcomeCertificate: "Certified Billing Morphologist™ (CBM – Expert)",
  },
];
